service: bedcon

provider:
  name: aws
  runtime: java8
  stage: demo
  region: eu-central-1
  memorySize: 256
  timeout: 30
  deploymentBucket: dasniko.serverless.deployments.${self:provider.region}

package:
  artifact: target/jug-demo.jar

functions:
  plain:
    handler: dasniko.serverless.jug.PlainFunction::greet
  hello:
    handler: dasniko.serverless.jug.HelloHandler
    events:
      - http:
          path: hello
          method: post
